steps:

- id: "rodando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

#- id: "Chown in /var/www"
  #name: 'gcr.io/cloud-builders/docker'
  #args: ['exec','-u','root','-t','app','chown','-R','www-data:www-data','/var/www']
  
- id: "rodando composer"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'composer', 'install']
  
- id: "compiando .env"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'cp', '.env.example', '.env']
  
- id: "rodando key:generate"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'key:generate']
  
- id: "rodando migrations"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'migrate']
  
- id: "rodando testes"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']

- id: "build imagem prod"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-laravel:$SHORT_SHA', '-f', 'Dockerfile.prod', '.']

- id: "push imagem"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/app-laravel:$SHORT_SHA']

- id: "ajustar deployment.yml - ks8"
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      sed 's#img-app-deployment#gcr.io/$PROJECT_ID/app-laravel:$SHORT_SHA#g' k8s/app/deployment.yaml > k8s/app/deployment--new.yaml;
      cat k8s/app/deployment--new.yaml;

- id: "deploy ks8"
      name: 'gcr.io/cloud-builders/kubectl'
      args:
        - 'apply'
        - '-f'
        - 'k8s/app/deployment--new.yaml'
        env:
        - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
        - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1'