apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa-dpy
spec:
  selector:
     matchLabels:
       app: go-hpa-dpy
  replicas: 1
  template:
    metadata:
      labels:
        app: go-hpa-dpy
    spec:
      containers:
      - name: go-hpa-pod
        image: devbrsam/fc-go-hpa:0.0.1
        ports:
        - containerPort: 8000

        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"